name: Auto-deployment of bertron-schema Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@main
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.10"

      - name: Build documentation and deploy to Github Pages
        run: |
          uv sync
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          # copy in the `about.md` and any other docs pages if they exist
          ([ ! -f docs/about.md ] && cp src/docs/*.md docs/) || true
          make mkd-gh-deploy
