name: Lint and Test

on:
    workflow_call:

jobs:

    run_linkml_tasks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - name: Repo checkout
              uses: actions/checkout@main

            - name: Set up Python 3.
              uses: actions/setup-python@main
              with:
                python-version: 3.12

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                # Install a specific version of uv.
                version: "0.6.10"

            - name: Install deps
              id: install_deps
              run: |
                uv sync

            - name: Lint linkml file
              id: lint_linkml
              run: |
                  make lint-no-warn
              continue-on-error: true

            - name: Validate sample data against the schema
              id: validate_sample_data
              run: |
                  make validate-examples
              continue-on-error: true

            - name: Test documentation generation
              id: test_docgen
              run: |
                make gendoc
              continue-on-error: true

            - name: outcome failure
              if: steps.lint_linkml.outcome != 'success' || steps.validate_sample_data.outcome != 'success' || steps.test_docgen.outcome != 'success'
              run: |
                  echo "linkml linting: ${{ steps.lint_linkml.outcome }}"
                  echo "sample data validation: ${{ steps.validate_sample_data.outcome }}"
                  echo "documentation generator: ${{ steps.test_docgen.outcome }}"
                  exit 1

            - name: outcome success
              if: steps.lint_linkml.outcome == 'success' && steps.validate_sample_data.outcome == 'success' && steps.test_docgen.outcome == 'success'
              run: |
                  echo All tests passed successfully!
                  exit 0
