name: Lint and Test

on:
    workflow_call:

jobs:

    run_linkml_tasks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - name: Repo checkout
              uses: actions/checkout@main

            - name: Set up Python 3.
              uses: actions/setup-python@main
              with:
                python-version: 3.12

            - name: Install Poetry and dependencies.
              run: |
                pipx install poetry
                poetry install

            - name: Lint linkml file
              id: lint_linkml
              run: |
                  poetry run linkml-lint ./src/bertron_schema/schema/bertron_schema.yaml --ignore-warnings
              continue-on-error: true

            - name: Validate sample data against the schema
              id: validate_sample_data
              run: |
                  poetry run linkml-validate -s ./src/bertron_schema/schema/bertron_schema.yaml ./src/data/examples/valid/*.json
              continue-on-error: true

            - name: Test documentation generation
              id: test_docgen
              run: |
                poetry install --with docs
                mkdir -p docs
                make gendoc
              continue-on-error: true

            - name: outcome failure
              if: steps.lint_linkml.outcome != 'success' || steps.validate_sample_data.outcome != 'success' || steps.test_docgen.outcome != 'success'
              run: |
                  echo "linkml linting: ${{ steps.lint_linkml.outcome }}"
                  echo "sample data validation: ${{ steps.validate_sample_data.outcome }}"
                  exit 1

            - name: outcome success
              if: steps.lint_linkml.outcome == 'success' && steps.validate_sample_data.outcome == 'success' && steps.test_docgen.outcome == 'success'
              run: |
                  echo "linkml linting: ${{ steps.lint_linkml.outcome }}"
                  echo "sample data validation: ${{ steps.validate_sample_data.outcome }}"
                  exit 0
